set_room_preference:
  fields:
    room_order:
      required: true
      selector:
        object:
    device_id:
      required: false
      selector:
        device:
          integration: karcher_home_robots

set_room_selection:
  fields:
    room_ids:
      required: true
      selector:
        object:
    device_id:
      required: false
      selector:
        device:
          integration: karcher_home_robots
